# What we want to call our workflow
name: Git Actions Demo
# The workflow / CI Server runs / triggers when there is a push to the repo
on: [push]
# What jobs do we want as part of our workflow
jobs:
  actions_demo:
    runs-on: ubuntu-latest  # Creating a container (virtual machine) that uses ubuntu
    # What do we want this machine to do?
    steps:
    - run: echo "Hello World!"
    - run: touch New_File
    - run: echo "I hope this works" > New_File
    - run: cat New_File
    - run: ls -a
    - run: pwd
    - run: echo $USER
    - run: git clone https://github.com/ryho03/Scripting
    - run: cat Scripting/README.md

  better_action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # Checking out and using the repo assigned to this workflow
    - run: chmod +x cool_script.sh  # Granting permission access to our script
    - run: ./cool_script.sh # Running our script
